spring.datasource.url=jdbc:postgresql://localhost:5433/rallytracker
spring.datasource.username=veitz
spring.datasource.password=$29TRCK
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true